version: "1.0"
info:
  model: int-scaffold
packages:
- name: Mir_wmugdemoProject
  gitServerName: mir_ibmwm
  gitUrl: https://github.com/mirhussainali
  gitUsername: mirhussainali
  gitBranch: main
- name: UserGroupDemo
  version: "1.0"
  gitServerName: mir_ibmwm
  gitUrl: https://github.com/mirhussainali
  gitUsername: mirhussainali
  gitBranch: main
services:
- serviceName: project.mir_wmugdemo.integrations:FirstFlow
  packages:
  - name: Mir_wmugdemoProject
    version: "1.0"
  - name: UserGroupDemo
    version: "1.0"
- serviceName: usergroupdemo.flowservices:welcomeService1
  packages:
  - name: UserGroupDemo
    version: "1.0"
- serviceName: pub.flow:getLastFailureCaught
  packages:
  - name: WmPublic
    version: 11.1.0.0.1
configurationVariables:
  jdbc.jdbcTestPool.waitingThread: "0"
  jdbc.jdbcTestPool.minConns: "0"
  jdbc.jdbcTestPool.snoopenabled: "false"
  jdbc.jdbcTestPool.expireTime: "60000"
  jdbc.jdbcTestPool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/jdbcTestPool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.jdbcTestPool.password: "{AES}er+I3U8nDVm8F4DBRST1+A=="
  jdbc.jdbcTestPool.spyparms: SpyAttributes=(log=(file)logs/spy/jdbcTestPool.log;logTName=yes;timestamp=yes)
  jdbc.jdbcTestPool.dbURL: jdbc:mysql://mysql.test.local:3306/webm
  jdbc.jdbcTestPool.poolThreshold: "0"
  jdbc.jdbcTestPool.maxConns: "10"
  jdbc.jdbcTestPool.userid: root
  jdbc.jdbcTestPool.driverAlias: MySQL Database Java Connector Driver
  jdbc.jdbcTestPool.useSSL: "false"
  jdbc.jdbcTestPool.spyenabled: "false"
